@startuml

package SystemServices <<Frame>> {
  class sys_mng
  {
    ~smng_state: static sys_mng_state_t
    +sys_mng_init(): uing32_t
    +sys_mng_loop(): uint32_t
    ~sys_mng_topic_btn_cb_func(): void
  }

  class sys_btn
  {
    +sys_btn_init()
    +sys_btn_loop()
  }

  class sys_led
  {
    +sys_led_init(): uint32_t
    +sys_led_loop(): uint32_t
    ~sys_led_topic_led_cb_func(): void
  }

  class sys_data_mng
  {
    ~sdatamng_buff[]: static uint8_t
    ~sdatamng_buff_top: static uint32_t
    ~sdatamng_topics[]: static uint8_t
    ~sdatamng_num_topic: static uint32_t
    ~sdatamng_rx_buff[]: static uint8_t
    ~sdatamng_param_buff[]: static uint8_t
    +sys_data_mng_init(): uint32_t
    +sys_data_mng_create_topic(): uint32_t
    +sys_data_mng_subscribe_topic(): uint32_t
    +sys_data_mng_publish_topic(): uint32_t
  }
}

@enduml