@startuml

participant USER as "User"
participant DRV_BTN as "driver button"
participant BSP_BTN as "BSP button"
participant SYS_BTN as "System button"
participant SYS_MNG as "System manager"
participant SYS_LED as "System led"
participant BSP_LED as "BSP led"

skinparam dpi 300

USER    --> DRV_BTN: User using button

DRV_BTN --> BSP_BTN: Debounce and send button event

BSP_BTN --> SYS_BTN: Send button event

SYS_BTN --> SYS_MNG: Send button event

SYS_MNG --> SYS_LED: Send effect message

SYS_LED --> BSP_LED: Control led

@enduml